/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seesideproductions_blinken_controllers_MyDMXController */

#ifndef _Included_com_seesideproductions_blinken_controllers_MyDMXController
#define _Included_com_seesideproductions_blinken_controllers_MyDMXController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seesideproductions_blinken_controllers_MyDMXController
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seesideproductions_blinken_controllers_MyDMXController_open
  (JNIEnv *, jobject);

/*
 * Class:     com_seesideproductions_blinken_controllers_MyDMXController
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seesideproductions_blinken_controllers_MyDMXController_close
  (JNIEnv *, jobject);

/*
 * Class:     com_seesideproductions_blinken_controllers_MyDMXController
 * Method:    set
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_seesideproductions_blinken_controllers_MyDMXController_set
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
