/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seesideproductions_blinken_controllers_DasController */

#ifndef _Included_com_seesideproductions_blinken_controllers_DasController
#define _Included_com_seesideproductions_blinken_controllers_DasController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seesideproductions_blinken_controllers_DasController
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL _Java_com_seesideproductions_blinken_controllers_DasController_open
  (JNIEnv *, jobject);

/*
 * Class:     com_seesideproductions_blinken_controllers_DasController
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL _Java_com_seesideproductions_blinken_controllers_DasController_close
  (JNIEnv *, jobject);

/*
 * Class:     com_seesideproductions_blinken_controllers_DasController
 * Method:    set
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL _Java_com_seesideproductions_blinken_controllers_DasController_set
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
